id: P6356A459
initial_creation_type: input
source_metadata:
  title: Chokling Tersar Series
  language: nl
  description: 'Texts related to the Chokling Tersar (mchog gling gter gsar), the
    New Treasures of Chokgyur Lingpa (1829–1870):'
  volume:
    183c7c782f174f2d9c5cf3879e4eb760:
      title: 'Advice on Nonsectarianism (from Radiant Sunlight of the Victorious Ones''
        Teachings: A Brief, First-Hand Account of the Liberating Life-Story of the
        Great Emanated Treasure Revealer)'
      parent: Advice
    676ecf8283ed41ab8b5d11c05ba5462b:
      title: Pithy Advice on Checking One's Progress on the Path
      parent: Advice
    37bd4f2221f94d7a990d6ba9d12b6299:
      title: The Aspiration of the Vajradhātu Maṇḍala
      parent: Aspiration Prayers
    c57159814e1546848b3d1874a9afcd1f:
      title: 'Radiant Sunlight of the Victors’ Teachings: A Brief, First-Hand Account
        of the Liberating Life-Story of the Great Emanated Treasure Revealer'
      parent: Biography
    361fac45775a47f598f988782f4cf490:
      title: 'The Wish-Fulfilling Tree: The Life Story of the Master of Uḍḍiyāna
        as found in Padmasambhava’s Sevenfold Cycle of Profundity'
      parent: Biography
    7517576c5b644909a89aa1162bbdd269:
      title: Concise Offering of the Body from the Root Text of the Heart Accomplishment
        of the Guru Tukdrup, The Essential Manual of Oral Instructions (Shaldam Nyingjang)
      parent: Chöd
    91f1d9277946482090e73c1f667a55e8:
      title: The Ornament of Padmasambhava’s Enlightened Vision
      parent: Commentaries
    585576661e92410584696bd02d7cbf07:
      title: 'The Vajra Words Unveiled: A Commentary on the Düsum Sangyé Prayer to
        the Guru'
      parent: Commentaries
    1fe4040817a241798aefc2178005da74:
      title: The Lament of Rudra
      parent: Confession
    2bf79595a16f49f3b17bbd103ee7f694:
      title: 'The Garland of Utpala Flowers: A Prayer to the Masters of the Lineage
        of Zabtik Drolchok'
      parent: Lineage Prayers
    e5bbb0d3940a4de1b4ad294e3c26083c:
      title: The Prayer Which Removes All Obstacles from the Path (Barché Lamsel)
      parent: Prayers
    7719763d5e894c0e8fccae706459ae43:
      title: The Prayer in Six Vajra Lines
      parent: Prayers
    93f1d53d29de41fd9a5cbbf2d79bed54:
      title: 'The Prayer to Guru Rinpoche that Spontaneously Fulfils All Wishes (Sampa
        Lhundrupma) from The Guru’s Heart Practice: The Wish-Fulfilling Jewel'
      parent: Prayers
    638eacc6d444429eb06c0f5cd6d174dc:
      title: The Testament Prayer to Orgyen Rinpoche
      parent: Prayers
    50eb2a0a896144cdbc2ec30876fbc42a:
      title: The Single-Page Practice of the Guru of Great Bliss
      parent: Sādhanas
    1de963288e21459d81c2d72df0089d21:
      title: Concise Daily Practice of Vajrasattva
      parent: Sādhanas
    079c632c685b4952bd60e74c43e39e83:
      title: Extremely Secret Unelaborate Daily Sādhana for the Heart Practice of
        the Great Demon-Slayer
      parent: Sādhanas
    af8f5dcc172e47fa8cd7d763adf26f86:
      title: White and Red Sur Offerings That Are Very Easy to Apply
      parent: Sur Offering
    65342d137faa4243aaccfe17d9e408aa:
      title: Vajrakīla Tsok Prayer from Sangtik Korsum
      parent: Tsok
created_at: '2022-03-01T03:13:53.995508'
last_modified_at: '2022-03-01T03:13:53.995510'
